<?php
$name = "Wako";
$food = "pizza";
$email = "fake@gmail.com";
$age = 21;
$users = 2;
$quantity = 3;
$gpa = 2.5;
$price = 4.99;
$tax_rate = 5.1;
$employed = true;
$online = true;
$for_sale = true;
echo "Hello {$name}";
echo "you like {$food} <br>";
echo "your email is {$email}<br>";
echo "you are {$age} old <br>";
echo "there are {$users} users online<br>";
echo "you would like to buy {$quantity} items <br>";
echo "your gap is {$gpa} <br>";
echo "your pizza is {$price} <br>";
echo "The sales tax rate is {$tax_rate}";
echo "online status: {$online}<br>";
